# -*- coding: utf-8 -*-
"""RAG Q&A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4S7y0U4M-fZx7X9JBoOQIaECEr_IUXj
"""

# Install libraries
!pip install langchain
!pip install pypdf
!pip install faiss-cpu
!pip install sentence-transformers
!pip install google-generativeai
!pip install langchain-huggingface

from google.colab import files

uploaded = files.upload()

!pip install langchain-community
from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("Humanities_report_final.pdf")
docs = loader.load()

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

chunks = splitter.split_documents(docs)

from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "all-MiniLM-L6-v2"
)

from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2"
)

db = FAISS.from_documents(
    chunks,
    embeddings
)

while True:
    question = input("Ask a question: ")

    results = db.similarity_search(question, k=5)

    context = "\n\n".join(
        [doc.page_content for doc in results]
    )

    prompt = f"""
    You are a helpful document assistant.

Answer ONLY from the provided context.

If the answer is not contained in the context, say:
"I could not find this information in the document."

    Context:
    {context}

    Question:
    {question}

    Answer:
    """

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    print("\nAnswer:")
    print(response.text)